# Generated by Django 5.2 on 2025-04-25 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Satwa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_individu', models.CharField(blank=True, max_length=100, null=True)),
                ('spesies', models.CharField(max_length=100)),
                ('asal_hewan', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('status_kesehatan', models.CharField(choices=[('Sehat', 'Sehat'), ('Sakit', 'Sakit'), ('Dalam Pemantauan', 'Dalam Pemantauan'), ('Lainnya', 'Lainnya')], max_length=30)),
                ('url_foto', models.URLField(blank=True, null=True)),
                ('habitat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datasatwa.habitat')),
            ],
            options={
                'unique_together': {('nama_individu', 'spesies', 'asal_hewan')},
            },
        ),
    ]
