# Generated by Django 5.2 on 2025-04-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('luas_area', models.IntegerField()),
                ('kapasitas_maksimal', models.IntegerField()),
                ('status_lingkungan', models.TextField()),
            ],
        ),
    ]
